# Generated by Django 5.0.6 on 2024-07-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0003_alter_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(default='', verbose_name='Ingredientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo',
            field=models.CharField(default=25, max_length=10, verbose_name='Tiempo'),
            preserve_default=False,
        ),
    ]
